once again, some build-system stuff
$(make install), $(make doc) and all those fun things just-work again

diff --git a/trunk/bedwyr/doc/Makefile.in b/trunk/bedwyr/doc/Makefile.in
--- a/trunk/bedwyr/doc/Makefile.in
+++ b/trunk/bedwyr/doc/Makefile.in
@@ -1,65 +1,119 @@
+##############################################################################
+#  Bedwyr prover                                                             #
+#  Copyright (C) 2012 Quentin Heath                                          #
+#                                                                            #
+#  This program is free software; you can redistribute it and/or modify      #
+#  it under the terms of the GNU General Public License as published by      #
+#  the Free Software Foundation; either version 2 of the License, or         #
+#  (at your option) any later version.                                       #
+#                                                                            #
+#  This program is distributed in the hope that it will be useful,           #
+#  but WITHOUT ANY WARRANTY; without even the implied warranty of            #
+#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
+#  GNU General Public License for more details.                              #
+#                                                                            #
+#  You should have received a copy of the GNU General Public License         #
+#  along with this code; if not, write to the Free Software Foundation,      #
+#  Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA              #
+##############################################################################
+
 # @configure_input@
 
-# DEFINITIONS
+### DEFINITIONS
 
 PACKAGE_TARNAME	= @PACKAGE_TARNAME@
 PACKAGE_VERSION	= @PACKAGE_VERSION@
 DIST_NAME	= $(PACKAGE_TARNAME)-$(PACKAGE_VERSION)
+ifeq ($(TARGET),)
+  TARGET_NAME	= $(PACKAGE_TARNAME)
+else
+  TARGET_NAME	= $(TARGET)
+endif
 
 SHELL	= @BASH@
+FIG2DEV	= @FIG2DEV@
 LATEX	= @LATEX@
 BIBTEX	= @BIBTEX@
-DVIPS	= @DVIPS@ -t a4 -Ppdf -z
-GZIP	= @GZIP@ -4 -f
-PS2PDF	= @PS2PDF@ -sPAPERSIZE=a4
+DVIPS	= @DVIPS@
+#DVIPS	= @DVIPS@ -t a4 -Ppdf -z
+PS2PDF	= @PS2PDF@
+#PS2PDF	= @PS2PDF@ -sPAPERSIZE=a4
 HEVEA	= @HEVEA@ png.hva
 BIBHVA	= @BIBHVA@
 IMAGEN	= @IMAGEN@ -png
 HACHA	= @HACHA@ -tocbis
 TAR	= @TAR@
+FIND	= @FIND@
+GZIP	= @GZIP@ -4 -f
 
-# FILES
+prefix		= @prefix@
+datarootdir	= @datarootdir@
+docdir		= $(patsubst %$(PACKAGE_TARNAME),%$(TARGET_NAME),@docdir@)
+htmldir		= @htmldir@
+pdfdir		= @pdfdir@
+psdir		= @psdir@
 
-QUICKSTART	= quickstart-1.4
-REFMAN		= refman-1.4
+HTMLDIR		= $(DESTDIR)$(htmldir)
+PDFDIR		= $(DESTDIR)$(pdfdir)
+PSDIR		= $(DESTDIR)$(psdir)
+
+INSTALL		= @INSTALL@
+INSTALL_OPTS	= -v
+INSTALL_DIR	= @INSTALL_PROGRAM@ $(INSTALL_OPTS) -d
+INSTALL_DATA	= @INSTALL_DATA@ $(INSTALL_OPTS) -p
+
+### FILES
+
+FIGDIR	= ./figures
+
+QUICKSTART	= quickstart
+REFMAN		= refman
 
 TEX_FILES	= $(QUICKSTART).tex $(REFMAN).tex
+TEX_INCLUDES	= $(wildcard include/*.tex)
+BIB_FILES	= $(wildcard *.bib)
+FIG_FILES	= $(wildcard $(FIGDIR)/*.fig )
+PSTEX		= $(FIG_FILES:.fig=.pstex)
+PSTEX_T		= $(FIG_FILES:.fig=.pstex_t)
+PIC_FILES	= $(FIG_FILES) \
+		  $(wildcard $(FIGDIR)/*.ps ) \
+		  $(wildcard $(FIGDIR)/*.eps)
 DVI_FILES	= $(TEX_FILES:.tex=.dvi)
-PSGZ_FILES	= $(DVI_FILES:.dvi=.ps.gz)
-PDF_FILES	= $(PSGZ_FILES:.ps.gz=.pdf)
+PS_FILES	= $(DVI_FILES:.dvi=.ps)
+PSGZ_FILES	= $(PS_FILES:=.gz)
+PDF_FILES	= $(PS_FILES:.ps=.pdf)
 HTML_FILES	= $(QUICKSTART).html $(REFMAN)/index.html
 
-TARGETS		= $(PSGZ) $(PDF) $(HTML)
+ARCH_FILES	= $(TEX_FILES) $(TEX_INCLUDES) $(BIB_FILES) \
+		  $(PIC_FILES) Makefile.in
 
-REFMAN_INCLUDES	=
-BIB_FILE	= userguide.bib
+TARGETS		= $(PSGZ_FILES) $(PDF_FILES) $(HTML_FILES)
 
-# BUILDING
+
+### BUILDING
 
 all: $(TARGETS)
 
-$(REFMAN).aux: $(REFMAN_INCLUDES)
-$(REFMAN).bbl: $(BIB_FILE)
+.SUFFIXES: .fig .pstex .pstex_t .tex .aux .bbl .dvi .ps .gz .pdf .haux .hbbl .html
 
-.SUFFIXES: .tex .aux .bbl .dvi .ps .gz .pdf .haux .hbbl .html
+.fig.pstex:
+	@$(FIG2DEV) -L pstex $< $@
 
-.tex.aux:
+.pstex.pstex_t:
+	@$(FIG2DEV) -L pstex_t -p $< $*.fig $@
+
+.tex.aux: $(TEX_INCLUDES)
 	@$(LATEX) $*
 
-.aux.bbl:
+# "|| true" avoid failure when there is no bib
+.aux.bbl: $(BIB_FILES)
 	@$(BIBTEX) $* || true
 
-# This cancels the predefined .tex.dvi rule,
-# which uses tex instead of latex,
-# and which I don't want to redefine since
-# depending on the bbl makes more sense dependency-wise.
-# For some reason, ".tex.dvi:" doesn't cancel the rule.
 %.dvi: %.tex
 
 .bbl.dvi:
 	@$(LATEX) $*
 	@while ( grep -q "Rerun to get cross-references right" $*.log ) ; do \
-	  echo 'Reruning latex to get cross-references right' ; \
 	  $(LATEX) $* ; \
 	  done
 
@@ -67,69 +121,77 @@ $(REFMAN).bbl: $(BIB_FILE)
 	@$(DVIPS) $*
 
 %.gz: %
-	@$(GZIP) -c $<
+	@$(GZIP) -c $< > $@
 
 .ps.pdf:
 	@$(PS2PDF) $<
 
-# The "-fix" option is needed to enforce the creation of $*.haux
-# even if $*.aux is still present frpom a previous latex run
-# (while hevea can use both, bibhva cannot).
+# "-fix" enforces the creation of $*.haux even if $*.aux is still present
+# from a previous latex run (while hevea can use both, bibhva cannot)
 .tex.haux:
-#	echo "\documentclass{article}\begin{document}\end{document}" > $*.image.tex
 	@$(HEVEA) -fix $*
 
 .haux.hbbl:
 	@$(BIBHVA) $*
 
 .hbbl.html:
-#	$(IMAGEN) $*
-#	@echo $(HEVEA) $*
-#	@while ( ($(HEVEA) $* 2>&1 | tee >(cat >&3) | grep -q "Rerun me to get cross-references right") 3>&1 ) ; do \
-	  echo "Reruning hevea to get cross-references right" ; \
-	  done
 	@$(HEVEA) -fix $*
 
 %/index.html: %.html
-	  @mkdir -p $*
-	  @$(HACHA) -o $@ $<
-	  @for i in $**.png ; do mv -vf $$i $*/ ; done
+	@mkdir -p $*
+	@$(HACHA) -o $@ $<
+	@for i in $(wildcard $**.png) ; do mv -vf $$i $*/ ; done
 
-# OTHER TARGETS
+### INSTALL
 
-.PHONY: archive manual.tar
+.PHONY: install
 
-archive: manual.tar
+install: install_psgz install_pdf install_html
 
-manual.tar: $(TEX_FILES) $(REFMAN_INCLUDES) $(BIB_FILE) Makefile.in
-	$(TAR) -cf $@ --xform 's|^|$(DIST_NAME)/doc/|' $^
+install_psgz: $(PSGZ_FILES)
+	@$(INSTALL_DIR) $(PSDIR)
+	@for i in $^ ; do $(INSTALL_DATA) $$i $(PSDIR) ; done
+	
+install_pdf: $(PDF_FILES)
+	@$(INSTALL_DIR) $(PDFDIR)
+	@for i in $^ ; do $(INSTALL_DATA) $$i $(PDFDIR) ; done
 
-# For this target, the aux file need to mention a bib file
-# in Dale's LIX directory.
-# Only he will be able to do the following command to create the
-# userguide.bib file.
-bib: $(BIB_FILE)
+install_html: install_html_quickstart install_html_refman
 
-BIBREF	= ../../../../../pap/references/master
-ifneq ($(strip $(wildcard $(BIBREF))),)
-$(BIB_FILE): $(REFMAN).tex
-	sed -e 's|^\\bibliography{userguide}$$|\\bibliography{$(BIBREF)}|' $< | $(LATEX) --jobname=$(<:.tex=) --
-	aux2bib $(<:.tex=.aux) > $@
-	rm -f $(<:.tex=.aux)
-endif
+install_html_quickstart: $(QUICKSTART).html
+	@$(INSTALL_DIR) $(HTMLDIR)
+	@$(INSTALL_DATA) $< $(HTMLDIR)
 
-.PHONY: tex_clean hevea_clean clean ocamldoc_clean distclean
-tex_clean:
-	@rm -fv *.aux *.out *.toc *.log *.dvi *.blg *.bbl *.idx *.ind *.ps
+install_html_refman: $(REFMAN)/index.html
+	@$(INSTALL_DIR) $(HTMLDIR)/$(REFMAN)
+	@for i in $(wildcard $(REFMAN)/*) ; do\
+	  $(INSTALL_DATA) $$i $(HTMLDIR)/$(REFMAN) ; done
 
-hevea_clean:
-	@rm -fv *.haux *.html *.blg *.hbbl *.image.tex *.htoc *.hidx *.hind *_motif.gif *.css
+### ARCHIVES
 
-clean: tex_clean hevea_clean
+.PHONY: archive
 
-ocamldoc_clean:
-	@rm -fv html/bedwyr/*
+archive: archive.tar
 
-distclean: clean ocamldoc_clean
-	@rm -fv $(TARGETS) *~
-	@rm -fvr $(REFMAN)/
+archive.tar: $(ARCH_FILES)
+	@$(TAR) -cf $@ --xform 's|^|$(DIST_NAME)/doc/|' $^
+
+### OTHER TARGETS
+
+.PHONY: clean_tex clean_hevea clean distclean
+
+clean_tex:
+	@find . \( -name \*.aux -o -name \*.bbl -o -name \*.blg \
+	  -o -name \*.log -o -name \*.idx -o -name \*.ilg -o -name \*.ind \
+	  -o -name \*.out -o -name \*.nav -o -name \*.snm -o -name \*.lox \
+	  -o -name \*.toc -o -name \*.lot -o -name \*.lof -o -name \*.vrb \) \
+	  -exec rm -vf {} \;
+
+clean_hevea:
+	@rm -fv *.haux *.html *.blg *.hbbl *.image.tex \
+	  *.htoc *.hidx *.hind *_motif.gif *.css
+	@rm -rvf $(REFMAN)
+
+clean: clean_tex clean_hevea
+	@$(FIND) . -name '*~' -exec rm -vf \{\} \;
+	@rm -vf *.dvi *.ps *.gz *.pdf *.tar
